//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalaxmiMarbal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabel_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabel_Customer()
        {
            this.Table_Bill = new HashSet<Table_Bill>();
            this.Table_OrderDeatils = new HashSet<Table_OrderDeatils>();
        }
    
        public int Cust_Id { get; set; }
        public string CustName { get; set; }
        public string CustPh { get; set; }
        public string CustAddress { get; set; }
        public string CustEmail { get; set; }
        public string Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Bill> Table_Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_OrderDeatils> Table_OrderDeatils { get; set; }
    }
}
