//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalaxmiMarbal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Order()
        {
            this.Table_OrderDeatils = new HashSet<Table_OrderDeatils>();
        }
    
        public int OId { get; set; }
        public string TotalAmount { get; set; }
        public string TotalPaid { get; set; }
        public string RemainingAmount { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_OrderDeatils> Table_OrderDeatils { get; set; }
    }
}
